{"uuid":"7f297dbc-3a37-4dc6-85ae-de24c9bc2892","historyId":"aadde080cabcbe3c9713fe0a3b2c4015","fullName":"automationEx.InvalidLoginTest.test2loginToYourAccountVisible","labels":[{"name":"package","value":"automationEx.InvalidLoginTest"},{"name":"testClass","value":"automationEx.InvalidLoginTest"},{"name":"testMethod","value":"test2loginToYourAccountVisible"},{"name":"parentSuite","value":"Default Suite"},{"name":"suite","value":"TestAutomation"},{"name":"subSuite","value":"automationEx.InvalidLoginTest"},{"name":"host","value":"mazen-ismail"},{"name":"thread","value":"6320@mazen-ismail.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"},{"name":"severity","value":"critical"}],"links":[],"name":"test2loginToYourAccountVisible","status":"skipped","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"src\\test\\resources\\testDataJsonFiles\\automationEx.json (The system cannot find the path specified)","trace":"java.lang.AssertionError: src\\test\\resources\\testDataJsonFiles\\automationEx.json (The system cannot find the path specified)\r\n\tat org.testng.Assert.fail(Assert.java:111)\r\n\tat utiliteis.JsonFileManager.<init>(JsonFileManager.java:26)\r\n\tat automationEx.InvalidLoginTest.beforeClass(InvalidLoginTest.java:26)\r\n\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:580)\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:71)\r\n\tat org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:400)\r\n\tat org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:333)\r\n\tat org.testng.internal.invokers.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:188)\r\n\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)\r\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1597)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:739)\r\n\tat org.testng.TestRunner.run(TestRunner.java:614)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:421)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:312)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1208)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1112)\r\n\tat org.testng.TestNG.run(TestNG.java:1079)\r\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)\r\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)\r\n"},"stage":"finished","description":"Asser Login Error Message Appears","steps":[],"attachments":[],"parameters":[],"start":1734291290309,"stop":1734291290311}